[package]
name = "limg-core"
version = "0.1.0"
edition = "2024"
license = "MIT"

description = "no_std limg core package"
readme = "README.md"
repository = "https://github.com/limg-projects/limg-core-rs"
publish = false
