name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  doc:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Extract crate version
        id: crate-version
        run: echo "CRATE_VERSION=$(cargo pkgid | sed 's/.*@//')" >> "$GITHUB_OUTPUT"
      - name: Generate documentation
        run: cargo doc --no-deps
      - name: Prepare directory
        run: |
          mkdir -p "${{ steps.crate-version.outputs.CRATE_VERSION }}"
          cp -r target/doc/* "${{ steps.crate-version.outputs.CRATE_VERSION }}/"
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ steps.crate-version.outputs.CRATE_VERSION }}"

  deploy:
    needs: doc
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
